// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpPok.Database;

namespace SharpPok.Database.Migrations
{
    [DbContext(typeof(PokDatabaseContext))]
    partial class PokDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SharpPok.Database.Model.Package", b =>
                {
                    b.Property<string>("packageID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("packageID");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("SharpPok.Database.Model.Version", b =>
                {
                    b.Property<string>("VersionID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PackageID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("VersionID");

                    b.HasIndex("PackageID");

                    b.ToTable("Version");
                });

            modelBuilder.Entity("SharpPok.Database.Model.Version", b =>
                {
                    b.HasOne("SharpPok.Database.Model.Package", null)
                        .WithMany("versions")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharpPok.Database.Model.Package", b =>
                {
                    b.Navigation("versions");
                });
#pragma warning restore 612, 618
        }
    }
}
